yamlmodels:
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: stock
        tests:
          - not_null
      - name: price
        tests:
          - not_null
  - name: stg_carts
    columns:
      - name: id
        tests:
        - unique
        - not_null
      - name: user_id
        tests:
        - relationships:
            to: ref('stg_users')
            field: id
      - name: total
        tests:
        - not_null
      - name: discounted_total
        tests:
        - not_null
      - name: total_products
        tests:
        - not_null
      - name: total_quantity
        tests:
        - not_null
  - name: stg_users
    columns:
      - name: id
        tests:
        - unique
        - not_null

