select
    raw_data:id::INT as id,
    raw_data:title::VARCHAR as title,
    raw_data:description::VARCHAR as description,
    raw_data:category::VARCHAR as category,
    raw_data:price::FLOAT as price,
    raw_data:discountPercentage::FLOAT as discount_percentage,
    raw_data:rating::FLOAT as rating,
    raw_data:stock::INT as stock,
    raw_data:brand::VARCHAR as brand,
    raw_data:sku::VARCHAR as sku,
    raw_data:weight::FLOAT as weight,
    raw_data:dimensions:width::FLOAT as width,
    raw_data:dimensions:height::FLOAT as height,
    raw_data:dimensions:depth::FLOAT as depth,
    raw_data:warrantyInformation::VARCHAR as warranty_info,
    raw_data:shippingInformation::VARCHAR as shipping_info,
    raw_data:availabilityStatus::VARCHAR as availability_status,
    raw_data:returnPolicy::VARCHAR as return_policy,
    raw_data:minimumOrderQuantity::INT as minimum_order_quantity,
    raw_data:meta:barcode::VARCHAR as barcode,
    raw_data:meta:createdAt::TIMESTAMP as created_at,
    raw_data:meta:updatedAt::TIMESTAMP as updated_at,
    extracted_at
from {{ source('tradeflow_raw', 'raw_products') }}